### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#234]
Have built release, zipped it up. I then unzipped on another PC, but it failed with the below error.

There is a folder in the place where it's looking, but it's a different version:
![image](https://user-images.githubusercontent.com/1108513/73091857-37002780-3ed3-11ea-9ab8-98cc97f41357.png)

But, I'm not sure what versions 64 and 72 refer to.

It _looks like_ I need to know the version of node on the target network, and ensure I compile Serge on a PC with the same version of node.

```
C:\git\20200123_serge\serge>yarn serge
yarn run v1.19.1
$ yarn start:server
$ cd packages/server && yarn start
$ node main.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\git\20200123_serge\serge\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\git\20200123_serge\serge\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by IanMayo** [comment]
Ian solved this by ensuring both systems were running the identical version of node.
