### ISSUE TITLE
Run-time console errors/warnings

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2467]
We currently have some react errors and material-table warnings as Serge starts.

We should address the technical debt, and fix them.

Maybe it's best for @lilitkarapetyan  to do the `react` ones, and @philb89  to do the `material-table` ones.

```
Warning: React has detected a change in the order of Hooks called by ChannelTabsContainer. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useState                   useState
3. useRef                     useRef
4. useContext                 useContext
5. useContext                 useContext
6. useState                   useState
7. useState                   useState
8. useEffect                  useEffect
9. useEffect                  useEffect
10. useEffect                 useEffect
11. undefined                 useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in ChannelTabsContainer (at GameChannels.tsx:169)
    in div (at GameChannels.tsx:168)
    in div (at GameChannels.tsx:166)
    in GameChannels (at GameChannelsWithTour.tsx:169)
    in div (at GameChannelsWithTour.tsx:168)
    in div (at GameChannelsWithTour.tsx:167)
    in GameChannelsWithTour (at PlayerUi.tsx:117)
    in PlayerUi (created by Connect(PlayerUi))
    in Connect(PlayerUi) (at PlayerUiWrapper.jsx:9)
    in PlayerStateProvider (at PlayerUiWrapper.jsx:7)
    in PlayerUiWrapper (at RouterMain.jsx:14)
    in RouterMain (at App.jsx:20)
    in ThemeProvider (at App.jsx:19)
    in Provider (at App.jsx:18)
    in App (at src/index.jsx:5)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2655
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
warnOnHookMismatchInDev @ react-dom.development.js:14715
updateHookTypesDev @ react-dom.development.js:14674
useContext @ react-dom.development.js:15895
useContext @ react.development.js:1493
usePlayerUiDispatch @ PlayerUi.tsx:46
factory @ factory.tsx:32
ChannelTabsContainer @ ChannelTabsContainer.tsx:73
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
beginWork @ react-dom.development.js:18610
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
dispatchAction @ react-dom.development.js:15660
_callee$ @ ChannelTabsContainer.tsx:38
tryCatch @ regeneratorRuntime.js:72
(anonymous) @ regeneratorRuntime.js:55
(anonymous) @ regeneratorRuntime.js:97
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
initialize @ ChannelTabsContainer.tsx:35
(anonymous) @ ChannelTabsContainer.tsx:43
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
index.tsx:108 my messages 0
index.tsx:129 initialising columns
index.tsx:39 only show false
index.tsx:73 only show 2 false
index.tsx:129 initialising columns
```
```
index.js:1 Warning: Failed prop type: Invalid prop `children` supplied to `ForwardRef(Tooltip)`. Expected an element that can hold a ref. Did you accidentally use a plain function component for an element instead? For more information see https://mui.com/r/caveat-with-refs-guide
    in ForwardRef(Tooltip) (created by MTableToolbar)
    in MTableToolbar (created by ForwardRef(MTableToolbarRef))
    in ForwardRef(MTableToolbarRef)
    in ForwardRef(MTableToolbarRef) (created by Toolbar)
    in div (created by Toolbar)
    in Toolbar (created by MaterialTable)
    in div (created by MuiPaperRoot)
    in MuiPaperRoot (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by Container)
    in Container (created by ForwardRef(ContainerRef))
    in ForwardRef(ContainerRef) (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
    in Unknown (created by Wrapped)
    in Provider (created by Wrapped)
    in Wrapped (created by PlanningAssets)
    in PlanningAssets (created by SupportPanel)
    in div (created by SupportPanel)
    in div (created by SupportPanel)
    in div (created by Resizable)
    in Resizable (created by Rnd)
    in DraggableCore (created by Draggable)
    in Draggable (created by Rnd)
    in Rnd (created by SupportPanel)
    in div (created by Transition)
    in Transition (created by ForwardRef(Slide))
    in ForwardRef(Slide) (created by SupportPanel)
    in div (created by SupportPanel)
    in SupportPanel
    in SupportPanel (created by PlanningChannel)
    in div (created by PlanningChannel)
    in PlanningChannel
    in PlanningChannel (at factory.tsx:187)
    in div (created by Tab)
    in Tab (created by Layout)
    in div (created by Layout)
    in Layout (at ChannelTabsContainer.tsx:71)
    in div (at ChannelTabsContainer.tsx:67)
    in ChannelTabsContainer (at GameChannels.tsx:169)
    in div (at GameChannels.tsx:168)
    in div (at GameChannels.tsx:166)
    in GameChannels (at GameChannelsWithTour.tsx:169)
    in div (at GameChannelsWithTour.tsx:168)
    in div (at GameChannelsWithTour.tsx:167)
    in GameChannelsWithTour (at PlayerUi.tsx:117)
    in PlayerUi (created by Connect(PlayerUi))
    in Connect(PlayerUi) (at PlayerUiWrapper.jsx:9)
    in PlayerStateProvider (at PlayerUiWrapper.jsx:7)
    in PlayerUiWrapper (at RouterMain.jsx:14)
    in RouterMain (at App.jsx:20)
    in ThemeProvider (at App.jsx:19)
    in Provider (at App.jsx:18)
    in App (at src/index.jsx:5)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2655
printWarning @ checkPropTypes.js:20
checkPropTypes @ checkPropTypes.js:83
validatePropTypes @ react.development.js:1714
createElementWithValidation @ react.development.js:1813
renderSearch @ index.js:150
MTableToolbar @ index.js:295
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ react-dom.development.js:18596
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
dispatchAction @ react-dom.development.js:15660
_callee$ @ ChannelTabsContainer.tsx:38
tryCatch @ regeneratorRuntime.js:72
(anonymous) @ regeneratorRuntime.js:55
(anonymous) @ regeneratorRuntime.js:97
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
initialize @ ChannelTabsContainer.tsx:35
(anonymous) @ ChannelTabsContainer.tsx:43
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
```
```
index.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef(Tooltip)`.
    in Search (created by ForwardRef(Tooltip))
    in ForwardRef(Tooltip) (created by MTableToolbar)
    in div (created by MuiInputAdornmentRoot)
    in MuiInputAdornmentRoot (created by ForwardRef(InputAdornment))
    in ForwardRef(InputAdornment) (created by MTableToolbar)
    in div (created by MuiInputRoot)
    in MuiInputRoot (created by ForwardRef(InputBase))
    in ForwardRef(InputBase) (created by ForwardRef(Input))
    in ForwardRef(Input) (created by ForwardRef(TextField))
    in div (created by MuiFormControlRoot)
    in MuiFormControlRoot (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by MuiTextFieldRoot)
    in MuiTextFieldRoot (created by ForwardRef(TextField))
    in ForwardRef(TextField) (created by MTableToolbar)
    in div (created by MuiToolbarRoot)
    in MuiToolbarRoot (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by MTableToolbar)
    in MTableToolbar (created by ForwardRef(MTableToolbarRef))
    in ForwardRef(MTableToolbarRef)
    in ForwardRef(MTableToolbarRef) (created by Toolbar)
    in div (created by Toolbar)
    in Toolbar (created by MaterialTable)
    in div (created by MuiPaperRoot)
    in MuiPaperRoot (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by Container)
    in Container (created by ForwardRef(ContainerRef))
    in ForwardRef(ContainerRef) (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
    in Unknown (created by Wrapped)
    in Provider (created by Wrapped)
    in Wrapped (created by PlanningAssets)
    in PlanningAssets (created by SupportPanel)
    in div (created by SupportPanel)
    in div (created by SupportPanel)
    in div (created by Resizable)
    in Resizable (created by Rnd)
    in DraggableCore (created by Draggable)
    in Draggable (created by Rnd)
    in Rnd (created by SupportPanel)
    in div (created by Transition)
    in Transition (created by ForwardRef(Slide))
    in ForwardRef(Slide) (created by SupportPanel)
    in div (created by SupportPanel)
    in SupportPanel
    in SupportPanel (created by PlanningChannel)
    in div (created by PlanningChannel)
    in PlanningChannel
    in PlanningChannel (at factory.tsx:187)
    in div (created by Tab)
    in Tab (created by Layout)
    in div (created by Layout)
    in Layout (at ChannelTabsContainer.tsx:71)
    in div (at ChannelTabsContainer.tsx:67)
    in ChannelTabsContainer (at GameChannels.tsx:169)
    in div (at GameChannels.tsx:168)
    in div (at GameChannels.tsx:166)
    in GameChannels (at GameChannelsWithTour.tsx:169)
    in div (at GameChannelsWithTour.tsx:168)
    in div (at GameChannelsWithTour.tsx:167)
    in GameChannelsWithTour (at PlayerUi.tsx:117)
    in PlayerUi (created by Connect(PlayerUi))
    in Connect(PlayerUi) (at PlayerUiWrapper.jsx:9)
    in PlayerStateProvider (at PlayerUiWrapper.jsx:7)
    in PlayerUiWrapper (at RouterMain.jsx:14)
    in RouterMain (at App.jsx:20)
    in ThemeProvider (at App.jsx:19)
    in Provider (at App.jsx:18)
    in App (at src/index.jsx:5)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2655
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
validateFunctionComponentInDev @ react-dom.development.js:17578
mountIndeterminateComponent @ react-dom.development.js:17545
beginWork @ react-dom.development.js:18596
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
dispatchAction @ react-dom.development.js:15660
_callee$ @ ChannelTabsContainer.tsx:38
tryCatch @ regeneratorRuntime.js:72
(anonymous) @ regeneratorRuntime.js:55
(anonymous) @ regeneratorRuntime.js:97
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
initialize @ ChannelTabsContainer.tsx:35
(anonymous) @ ChannelTabsContainer.tsx:43
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
index.tsx:108 my messages 0
index.tsx:129 initialising columns
index.tsx:39 only show false
index.tsx:129 initialising columns
```
```
react_devtools_backend.js:2655 The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss. 
    at MaterialTable (http://localhost:3000/static/js/vendors~main.chunk.js:61386:37)
    at http://localhost:3000/static/js/vendors~main.chunk.js:61272:36
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:611634:28)
    at Wrapped
    at PlanningAssets (http://localhost:3000/static/js/main.chunk.js:40383:21)
    at div
    at div
    at div
    at Resizable (http://localhost:3000/static/js/vendors~main.chunk.js:509918:24)
    at DraggableCore (http://localhost:3000/static/js/vendors~main.chunk.js:547545:5)
    at Draggable (http://localhost:3000/static/js/vendors~main.chunk.js:546927:5)
    at Rnd (http://localhost:3000/static/js/vendors~main.chunk.js:561800:24)
    at div
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:573279:30)
    at Slide (http://localhost:3000/static/js/vendors~main.chunk.js:86952:24)
    at div
    at SupportPanel (http://localhost:3000/static/js/main.chunk.js:58907:28)
    at div
    at PlanningChannel (http://localhost:3000/static/js/main.chunk.js:43119:23)
    at div
    at Tab (http://localhost:3000/static/js/vendors~main.chunk.js:416018:24)
    at div
    at Layout (http://localhost:3000/static/js/vendors~main.chunk.js:415390:24)
    at div
    at ChannelTabsContainer (http://localhost:3000/static/js/main.chunk.js:93656:22)
    at div
    at div
    at GameChannels (http://localhost:3000/static/js/main.chunk.js:99284:26)
    at div
    at div
    at GameChannelsWithTour (http://localhost:3000/static/js/main.chunk.js:100006:17)
    at PlayerUi (http://localhost:3000/static/js/main.chunk.js:102889:23)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:560136:75)
    at PlayerStateProvider (http://localhost:3000/static/js/main.chunk.js:92557:23)
    at PlayerUiWrapper
    at RouterMain (http://localhost:3000/static/js/main.chunk.js:90418:130)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:244440:24)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:559877:20)
    at App (http://localhost:3000/static/js/main.chunk.js:85581:130)
overrideMethod @ react_devtools_backend.js:2655
componentDidUpdate @ material-table.js:858
commitLifeCycles @ react-dom.development.js:19835
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
dispatchAction @ react-dom.development.js:15660
_callee$ @ ChannelTabsContainer.tsx:38
tryCatch @ regeneratorRuntime.js:72
(anonymous) @ regeneratorRuntime.js:55
(anonymous) @ regeneratorRuntime.js:97
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:12
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
initialize @ ChannelTabsContainer.tsx:35
(anonymous) @ ChannelTabsContainer.tsx:43
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
index.tsx:108 my messages 0
```
```
react_devtools_backend.js:2655 The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss. 
    at MaterialTable (http://localhost:3000/static/js/vendors~main.chunk.js:61386:37)
    at http://localhost:3000/static/js/vendors~main.chunk.js:61272:36
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:611634:28)
    at Wrapped
    at PlanningAssets (http://localhost:3000/static/js/main.chunk.js:40383:21)
    at div
    at div
    at div
    at Resizable (http://localhost:3000/static/js/vendors~main.chunk.js:509918:24)
    at DraggableCore (http://localhost:3000/static/js/vendors~main.chunk.js:547545:5)
    at Draggable (http://localhost:3000/static/js/vendors~main.chunk.js:546927:5)
    at Rnd (http://localhost:3000/static/js/vendors~main.chunk.js:561800:24)
    at div
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:573279:30)
    at Slide (http://localhost:3000/static/js/vendors~main.chunk.js:86952:24)
    at div
    at SupportPanel (http://localhost:3000/static/js/main.chunk.js:58907:28)
    at div
    at PlanningChannel (http://localhost:3000/static/js/main.chunk.js:43119:23)
    at div
    at Tab (http://localhost:3000/static/js/vendors~main.chunk.js:416018:24)
    at div
    at Layout (http://localhost:3000/static/js/vendors~main.chunk.js:415390:24)
    at div
    at ChannelTabsContainer (http://localhost:3000/static/js/main.chunk.js:93656:22)
    at div
    at div
    at GameChannels (http://localhost:3000/static/js/main.chunk.js:99284:26)
    at div
    at div
    at GameChannelsWithTour (http://localhost:3000/static/js/main.chunk.js:100006:17)
    at PlayerUi (http://localhost:3000/static/js/main.chunk.js:102889:23)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:560136:75)
    at PlayerStateProvider (http://localhost:3000/static/js/main.chunk.js:92557:23)
    at PlayerUiWrapper
    at RouterMain (http://localhost:3000/static/js/main.chunk.js:90418:130)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:244440:24)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:559877:20)
    at App (http://localhost:3000/static/js/main.chunk.js:85581:130)
```

**Comment by lebaphi** [comment]
Hi @IanMayo, it looks like these errors happen inside the material table core, the search component and filter component are function components and cannot be given refs, if we set `options.search: false` and `options.filtering: false`, this error has gone.  I'm not sure if we can fix this 🤔
