### ISSUE TITLE
Serge.exe crashed about 5 times over 2 days

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#796]
On about 5 times I got to the "Game Control" PC, and saw the `executable_win.exe` command prompt had disappeared.

I associate this with the app crashing.  I wasn't able to develop a pattern for what could have triggered this.

I _guess_ I made SQLite manual changes on about 5 times, though I didn't notice this being at the same time as the server crashing.  But, this is certainly worth testing.  I know that there are some backend crashes from `yarn develop` triggered by some types of database change.

OK, able to reproduce this.  It's when `DB Browser For Sqlite` has a lock-file open for the wargame database.

Steps to reproduce:
- initiate wargame, play as Blue CO
- send message in Blue chat-room
- open database in `DB Browser`
- open `by-sequence` table
- open most recent entry
- make change to `content` of most recent message
- `apply`, then  `write changes`
- send another message in blue chat-room, all ok
- open `by-sequence` table again
- make  another change to `content` of most recent message
- `apply`, but **do not** `write changes` (I think this locks database)
- try to send another message - server will crash.

```
 /Users/ian/git/serge/node_modules/pouchdb-adapter-websql-core/lib/index.js:400
@serge/server:           var seq = res.rows.item(0).seq;
@serge/server:                                     ^
@serge/server: TypeError: Cannot read property 'seq' of undefined
@serge/server:     at SQLTask.sqlCallback (/Users/ian/git/serge/node_modules/pouchdb-adapter-websql-core/lib/index.js:400:37)
@serge/server:     at /Users/ian/git/serge/node_modules/websql/lib/websql/WebSQLTransaction.js:70:19
@serge/server:     at checkDone (/Users/ian/git/serge/node_modules/websql/lib/sqlite/SQLiteDatabase.js:50:7)
@serge/server:     at /Users/ian/git/serge/node_modules/websql/lib/sqlite/SQLiteDatabase.js:59:7
@serge/server:     at Statement.<anonymous> (/Users/ian/git/serge/node_modules/websql/lib/sqlite/SQLiteDatabase.js:21:5)
@serge/server: error Command failed with exit code 1.

```
The above code isn't in our code, it's in PouchDb code.

After further digging, I see there is a `-journal` _rollback_ file created between the `Apply` and `Write changes` events.

So, I guess PouchDb should only try to access the database if there isn't a _rollback_ file present.

**Comment by IanMayo** [comment]
Issue logged with PouchDb here: https://github.com/pouchdb/pouchdb/issues/8308

**Comment by IanMayo** [comment]
Closing.  PouchDb has deprecated SQLite support, but we don't have access to an alternate backend client.
